CLEO V2.0.0.7
cleolibrary/III.VC.CLEO pull request #19
Opened 2023-08-25 06:24 UTC by XMDS

2023-09-07 23:08 UTC, MiranDMC requested changes

2023-09-07 23:08 UTC, MiranDMC commented on source/III.VC.CLEO/Fxt.cpp
> +	for (uint8_t i = 0; i < 6; i++) {
This project is using "opening bracket in new line" style. Better keep it consistent.

2023-09-07 23:08 UTC, MiranDMC commented on source/III.VC.CLEO/Fxt.cpp
> +uint16_t CustomText::convert_utf8_to_utf16(uint8_t* utf8, uint16_t utf8_len, uint16_t* utf16, uint16_t utf16_len)
Use char\wchar_t for characters, int\unsigned int for counts.

2023-09-07 23:08 UTC, MiranDMC commented on source/III.VC.CLEO/Fxt.cpp
> +			utf16[length] = utf8[i] & (0xFF >> (bytes + 1));
Many magic in single line. How about creating variable named "mask", then using in. Comments would be nice too.

2023-09-07 23:08 UTC, MiranDMC commented on source/III.VC.CLEO/Fxt.cpp
> +				utf16[length] += utf8[i] & 0x3F;
Magic numbers? 0x3F comes out of blue without any explanation.

2023-09-07 23:08 UTC, MiranDMC commented on source/III.VC.CLEO/Fxt.cpp
> +				i++;
Can now **i** address out of data buffer?

2023-09-08 01:29 UTC, XMDS commented on source/III.VC.CLEO/Fxt.cpp
> +	uint16_t* u16_text = new uint16_t[len + 1];
In fact, it is better to use the uint16_t type, first of all it is more intuitive to tell us that it is 2 bytes (although the cleo library runs on win, but I have planned to port it to the mobile platform, the wchar_t type is not 2 bytes in some systems  ), another reason is that my experience in Chinese games tells me that you should never use the wchar_t type to save Chinese characters.

2023-09-08 01:30 UTC, XMDS commented on source/III.VC.CLEO/Fxt.cpp
> +	uint16_t* u16_text = new uint16_t[len + 1];
In fact, it is better to use the uint16_t type, first of all it is more intuitive to tell us that it is 2 bytes (although the cleo library runs on win, but I have planned to port it to the mobile platform, the wchar_t type is not 2 bytes in some systems  ), another reason is that my experience in Chinese games tells me that you should never use the wchar_t type to save Chinese characters.

2023-09-08 01:31 UTC, XMDS commented on source/III.VC.CLEO/Fxt.cpp
> +	memset(u16_text, 0, len + 1);
Yes.  I forgot, now it only has half the memory written with 0's.
Forgive me I prefer c style

2023-09-08 14:15 UTC, MiranDMC commented on source/III.VC.CLEO/Fxt.cpp
> +	uint16_t* u16_text = new uint16_t[len + 1];
Perhaps then
`typedef uint16_t wchar` is most elegant solution.

2023-10-06 14:40 UTC, MiranDMC commented
Please rebase on current master branch. We added some of similar changes already, so this PR will become simpler.

2023-11-05 07:43 UTC, closed without merging